// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { defineMcp } from "npm:@lovable.dev/mcp-js@0.26.2";

// src/lib/mcp/tools/list-listings.ts
import { defineTool } from "npm:@lovable.dev/mcp-js@0.26.2";
import { z } from "npm:zod@^4.4.3";

// src/lib/mcp/tools/_client.ts
import { createClient } from "npm:@supabase/supabase-js@^2.112.3";
function sb() {
  return createClient(
    process.env.SUPABASE_URL,
    process.env.SUPABASE_ANON_KEY ?? process.env.SUPABASE_PUBLISHABLE_KEY,
    { auth: { persistSession: false, autoRefreshToken: false } }
  );
}
var uid = () => `${Date.now().toString(36)}${Math.random().toString(36).slice(2, 7)}`;
var ok = (data) => ({
  content: [{ type: "text", text: JSON.stringify(data, null, 2) }],
  structuredContent: data
});
var fail = (message) => ({
  content: [{ type: "text", text: `Error: ${message}` }],
  isError: true
});

// src/lib/mcp/tools/list-listings.ts
var DAY = 864e5;
var list_listings_default = defineTool({
  name: "list_listings",
  title: "List listings",
  description: "List the items being sold, each with its price ladder, which phase is currently running, and how many days that phase is past its planned runtime. Read this before changing anything.",
  inputSchema: {
    includeSold: z.boolean().default(false).describe("Also return items already marked sold.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ includeSold }) => {
    const supabase = sb();
    let query = supabase.from("listings").select("*").order("created_at", { ascending: false });
    if (!includeSold) query = query.is("sold_at", null);
    const { data, error } = await query;
    if (error) return fail(error.message);
    const now = Date.now();
    const listings = (data ?? []).map((row) => {
      const phases = Array.isArray(row.phases) ? row.phases : [];
      let active = -1;
      phases.forEach((p, i) => {
        if (p.startedAt) active = i;
      });
      const running = active >= 0 ? phases[active] : null;
      const overdueDays = running && running.days && running.startedAt ? Math.floor((now - Date.parse(running.startedAt)) / DAY) - running.days : null;
      return {
        id: row.id,
        title: row.title,
        soldAt: row.sold_at,
        soldPrice: row.sold_price,
        activePhaseIndex: active,
        currentPrice: running ? running.price : null,
        currentPriceType: running ? running.priceType : null,
        overdueDays,
        due: overdueDays !== null && overdueDays >= 0,
        phases
      };
    });
    return ok({ listings, count: listings.length });
  }
});

// src/lib/mcp/tools/add-listing.ts
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.26.2";
import { z as z2 } from "npm:zod@^4.4.3";
var phase = z2.object({
  action: z2.string().describe('What has to happen on the platform first, e.g. "Neu einstellen".'),
  price: z2.number().nullable().describe("Price in euros, or null for a step that is not a price, such as giving the item away."),
  priceType: z2.enum(["VB", "FP"]).default("VB"),
  days: z2.number().int().min(0).describe("How long this price should run before the next step is owed. 0 means it never falls due, which is how a plan ends.")
});
var add_listing_default = defineTool2({
  name: "add_listing",
  title: "Add a listing",
  description: "Add an item to the tracker together with its whole price ladder. Use startedAt when the ad went live earlier than now, so the first phase counts from the right day.",
  inputSchema: {
    title: z2.string().min(1).describe("Shown on the card; the item, not the ad headline."),
    phases: z2.array(phase).min(1).describe("The ladder, in order, starting with the price it is listed at now."),
    startNow: z2.boolean().default(true).describe("True when the ad is already online, so the first phase starts running immediately."),
    startedAt: z2.string().optional().describe("ISO timestamp the first phase started. Overrides startNow.")
  },
  annotations: { readOnlyHint: false, idempotentHint: false, openWorldHint: false },
  handler: async ({ title, phases, startNow, startedAt }) => {
    const stamp = startedAt ?? (/* @__PURE__ */ new Date()).toISOString();
    const running = Boolean(startedAt) || startNow;
    const row = {
      id: uid(),
      title,
      photo: null,
      created_at: stamp,
      phases: phases.map((p, i) => ({
        id: uid(),
        action: p.action,
        price: p.price,
        priceType: p.priceType,
        days: p.days,
        startedAt: i === 0 && running ? stamp : null
      })),
      sold_at: null,
      sold_price: null
    };
    const { error } = await sb().from("listings").insert(row);
    if (error) return fail(error.message);
    return ok({ id: row.id, title: row.title, phases: row.phases });
  }
});

// src/lib/mcp/tools/update-phase.ts
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.26.2";
import { z as z3 } from "npm:zod@^4.4.3";
var update_phase_default = defineTool3({
  name: "update_phase",
  title: "Change or start a phase",
  description: "Change one phase of a listing \u2014 its price, runtime, type or label \u2014 and optionally stamp it as started, which is what happens when the ad has actually been re-posted at that price. Call list_listings first to get the index.",
  inputSchema: {
    listingId: z3.string().describe("Listing id from list_listings."),
    phaseIndex: z3.number().int().min(0).describe("Zero-based position in the ladder."),
    price: z3.number().nullable().optional(),
    priceType: z3.enum(["VB", "FP"]).optional(),
    days: z3.number().int().min(0).optional(),
    action: z3.string().optional(),
    start: z3.boolean().optional().describe("Stamp this phase as started now. Only true once the new ad is actually online."),
    clearStart: z3.boolean().optional().describe("Undo a start stamp that was set by mistake.")
  },
  annotations: { readOnlyHint: false, idempotentHint: false, openWorldHint: false },
  handler: async ({ listingId, phaseIndex, price, priceType, days, action, start, clearStart }) => {
    const supabase = sb();
    const { data, error } = await supabase.from("listings").select("phases").eq("id", listingId).single();
    if (error) return fail(error.message);
    const phases = Array.isArray(data?.phases) ? data.phases : [];
    if (phaseIndex >= phases.length) {
      return fail(`Listing has ${phases.length} phases, no index ${phaseIndex}.`);
    }
    const next = phases.map(
      (p, i) => i !== phaseIndex ? p : {
        ...p,
        ...price !== void 0 ? { price } : {},
        ...priceType !== void 0 ? { priceType } : {},
        ...days !== void 0 ? { days } : {},
        ...action !== void 0 ? { action } : {},
        ...start ? { startedAt: (/* @__PURE__ */ new Date()).toISOString() } : {},
        ...clearStart ? { startedAt: null } : {}
      }
    );
    const { error: writeError } = await supabase.from("listings").update({ phases: next }).eq("id", listingId);
    if (writeError) return fail(writeError.message);
    return ok({ listingId, phase: next[phaseIndex] });
  }
});

// src/lib/mcp/tools/mark-sold.ts
import { defineTool as defineTool4 } from "npm:@lovable.dev/mcp-js@0.26.2";
import { z as z4 } from "npm:zod@^4.4.3";
var mark_sold_default = defineTool4({
  name: "mark_sold",
  title: "Mark sold",
  description: "Close a listing. The price is what it actually fetched, which is rarely the asking price \u2014 pass null only when it genuinely is not known.",
  inputSchema: {
    listingId: z4.string(),
    price: z4.number().nullable().describe("What it sold for, in euros."),
    soldAt: z4.string().optional().describe("ISO timestamp, when it was not today.")
  },
  annotations: { readOnlyHint: false, idempotentHint: true, openWorldHint: false },
  handler: async ({ listingId, price, soldAt }) => {
    const { error } = await sb().from("listings").update({ sold_at: soldAt ?? (/* @__PURE__ */ new Date()).toISOString(), sold_price: price }).eq("id", listingId);
    if (error) return fail(error.message);
    return ok({ listingId, soldPrice: price });
  }
});

// src/lib/mcp/index.ts
var mcp_default = defineMcp({
  name: "kleinanzeigen-mcp",
  title: "Kleinanzeigen",
  version: "0.1.0",
  instructions: "Tools for a personal secondhand-selling tracker. Every listing carries a ladder of phases: a price, how many days that price should run, and the move on the platform that starts it. Use `list_listings` to see what is running and what is overdue, `add_listing` once an ad is online, `update_phase` to change a price or confirm that a re-post has happened, and `mark_sold` when the item is gone. A phase only counts as started when the ad actually exists at that price.",
  tools: [list_listings_default, add_listing_default, update_phase_default, mark_sold_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.26.2/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
